name: publish

permissions:
  contents: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: np version type (patch/minor/major)
        required: true
        default: patch
      distTag:
        description: npm dist-tag (latest,next,canary)
        required: false
        default: latest

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Install deps
        run: pnpm install --no-frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Publish with np (provenance enabled)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ "${{ inputs.distTag }}" != "latest" ]; then TAG_ARGS="--tag ${{ inputs.distTag }}"; fi
          npx np "${{ inputs.version }}" --no-tests --any-branch --yolo --message "release: %s" $TAG_ARGS


